### ISSUE TITLE
projection question

### ISSUE THREAD

**Issue by Andyen512** [DCVL-3D/PointHMR_release#2]
Thanks for your great work. I'd like to know how to do the 3d to 2d projection because the single view mesh estimation task don't have the cam parameters.

**Comment by jhkim0759** [comment]
Thank you for your interest! We used the estimated value of camera parameters for the projection

**Comment by Andyen512** [comment]
Could you give me some code and data link for reference? I'm not familiar with the projection.

**Comment by jhkim0759** [comment]
I'll release the code soon. To be familiar with the projection,  you can refer to the code from other methods such as Mesh Graphormer.

**Comment by Andyen512** [comment]
Thanks, looking forward to your code and I'll try Graphormer
