### ISSUE TITLE
About grid feature

### ISSUE THREAD

**Issue by imabackstabber** [DCVL-3D/PointHMR_release#3]
Hi, I've reading your paper, impressive work!
I've been wondering how the `grid tokens` work, I guess it is used to compensate the inaccurate point estimation? Have you guys done any ablation study about `grid tokens` and maybe can give some data when PointHMR is without grid token?

**Comment by jhkim0759** [comment]
I'm sorry. We haven't conducted the ablation study for grid tokens. However, we referred to the idea from MeshGraphormer, and the ablation study for the grid tokens is also provided in the paper. We thought that the grid features play an important role in approximately aligning the mesh structure to the image by preserving the entire image information.

**Comment by imabackstabber** [comment]
Ok, I might do an ablation experiment myself. Thanks for your reply.

**Comment by jhkim0759** [comment]
Thank you for your interest!
